esphome:
  name: fbh

  platformio_options:
    board_build.flash_mode: dio

  on_boot:
    then:
      - logger.log:
          format: "FBH Temperature Sensors started"
          level: INFO

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

# Enable logging
logger:
#  level: VERBOSE
  
# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB

one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  # - platform: dallas_temp
  #   address: 0x000000000d597c28
  #   name: temperature1
  #   update_interval: 30s
  #   filters:
  #     - calibrate_linear:
  #        datapoints:
  #         # Map from sensor to true value
  #         - 16.25 -> 16.58
  #         - 31.7 -> 31.76
  # - platform: dallas_temp
  #   address: 0x340000000d113528
  #   name: temperature2
  #   update_interval: 30s
  #   filters:
  #     - calibrate_linear:
  #        datapoints:
  #         # Map from sensor to true value
  #         - 16.6 -> 16.58
  #         - 31.7 -> 31.76
  # - platform: dallas_temp
  #   address: 0xa00000000dcd3028
  #   name: temperature3
  #   update_interval: 30s
  #   filters:
  #     - calibrate_linear:
  #        datapoints:
  #         # Map from sensor to true value
  #         - 16.3 -> 16.58
  #         - 31.4 -> 31.76
  - platform: dallas_temp
    address: 0x53f73e560a646128
    name: temperature4
    update_interval: 30s
    filters:
      - calibrate_linear:
         datapoints:
          # Map from sensor to true value
          - 16.8 -> 16.58
          - 31.9 -> 31.76
  - platform: dallas_temp
    address: 0x6dea27560a646128
    name: temperature5
    update_interval: 30s
    filters:
      - calibrate_linear:
         datapoints:
          # Map from sensor to true value
          - 16.8 -> 16.58
          - 31.8 -> 31.76
  - platform: dallas_temp
    address: 0x84e93d560a646128
    name: temperature6
    update_interval: 30s
    filters:
      - calibrate_linear:
         datapoints:
          # Map from sensor to true value
          - 16.7 -> 16.58
          - 31.9 -> 31.76
  - platform: dallas_temp
    address: 0x8ab42c560a646128
    name: temperature7
    update_interval: 30s
    filters:
      - calibrate_linear:
         datapoints:
          # Map from sensor to true value
          - 16.6 -> 16.58
          - 31.8 -> 31.76
  - platform: dallas_temp
    address: 0x4a322e560a646128
    name: temperature8
    update_interval: 30s
    filters:
      - calibrate_linear:
         datapoints:
          # Map from sensor to true value
          - 16.6 -> 16.58
          - 31.9 -> 31.76

web_server:
prometheus:
